### ISSUE TITLE
Incorrectly set openzeppelin-solidity version

### ISSUE THREAD

**Issue by eMarchenko** [levelkdev/tidbit#12]
In `pachage.json` openzeppelin-solidity is added as follows:
```
"dependencies": {
    "openzeppelin-solidity": "^1.12.0",
},
```
As said in [readme](https://github.com/OpenZeppelin/openzeppelin-solidity/tree/v1.12.0#installing-openzeppelin) for v1.12.0, "OpenZeppelin does not currently follow semantic versioning". So one should include this library as `"openzeppelin-solidity": "1.12.0",`.

Fortunately, this should not cause any serious problems:
* this repo includes `package-lock.json` with OZ version set to `1.12.0`
* there is no newer compatible version of OZ, as next version is v2.0.0.

**Comment by monoidz** [comment]
Fixed in recent PR. #15
