### ISSUE TITLE
Same signature can be reused in SignedMultiOracle

### ISSUE THREAD

**Issue by maxsam4** [levelkdev/tidbit#13]
The id being set is not part of the data being signed. This means that after one legit signature has been broadcasted, it can be used to set result at all the possible id. Albeit the same result will be set always, it can still really mess up things especially when this is combined with front-running attacks to set incorrect data just before the actual transaction to set a result at a new id is mined.

**Comment by cwhinfrey** [comment]
Great catch @maxsam4! Really appreciate you raising this. We'll add the `id` as part of the signed message. Also, for both `SignedOracle` and `SignedMultiOracle` we'll add the contract address to the signed message to prevent similar replay attacks across oracle contracts.

**Comment by cwhinfrey** [comment]
Thanks again for reporting @maxsam4!
